### ISSUE TITLE
Add docs and changelog for custom rules

### ISSUE THREAD

**Issue by danielcompton** [jonase/kibit#140]
https://github.com/jonase/lein-kibit/pull/5 and #139 from @kapilreddy allow us to provide custom rules. We need to write docs and examples for this, and update the changelog with this and the change in args for external consumers of the kibit library.

**Comment by kapilreddy** [comment]
@danielcompton I have updated README. Let me know if we want to add more to the custom rules section.

**Comment by danielcompton** [comment]
Sorry for dragging my heels on this, I've got a ClojureBridge coming up, so most of my extra time is going towards that. I'll take a look as soon as I can.

**Comment by marksto** [comment]
Hi @danielcompton! This one still isn't merged and it looks like an accident. Are there any plans to finally merge this one together with the #139 (the functionality itself)?

**Comment by jtrunick** [comment]
I'd like to just use the rules I put in the rules folder. Is this possible?
